name: cookbook
description: Cookbook, a Flutter showcase project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^1.4.1
  flutter_hooks: ^0.13.1
  package_info: ^0.4.1
  provider: ^4.3.1
  share: ^0.6.4+3
  shared_preferences: ^0.5.8
  shimmer: ^1.1.1
  url_launcher: ^5.5.0
  youtube_player_iframe: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
